services:
  motbiapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: motbi-docker
    container_name: motbiapp
    restart: always
    ports:
      - "8080:8080"  # Expone el puerto 8080 en el contenedor y en el host
    environment:
      POSTGRESDB: ${POSTGRESDB}
      PORT: 8080
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: postgres:16.3
    container_name: motbidb
    restart: always
    ports:  
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db:/var/lib/postgresql/data
