name: Deploy to EC2

on:
  push:
    branches:
      - main  # O la rama que desees monitorear

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-136-160-175.us-east-2.compute.amazonaws.com "mkdir -p /home/ec2-user/motbi-backend"
          scp -o StrictHostKeyChecking=no -r ./* ec2-user@ec2-3-136-160-175.us-east-2.compute.amazonaws.com:/home/ec2-user/motbi-backend

      # - name: Install Docker
      #  run: |
      #    ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-ip "sudo yum update -y && sudo yum install docker -y && sudo systemctl start docker && sudo systemctl enable docker"

      - name: Deploy using Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-136-160-175.us-east-2.compute.amazonaws.com "cd /home/ec2-user/motbi-backend && sudo docker-compose down && sudo docker-compose up -d --build"
